These are my macOS shortcut hacks using some combination of Karabiner-Elements and Hammerspoon.

== Background:

Hat tip: This started out as a fork of [https://github.com/lodestone/hyper-hacks]. Thanks @lodestone!

http://brettterpstra.com/2012/12/08/a-useful-caps-lock-key/[Hyper key hack]

Check out the link:https://github.com/lodestone/hyper-hacks/wiki[Wiki] for ideas on how to configure your `init.lua`.

== Installation:

* Install link:http://www.hammerspoon.org[Hammerspoon]
* Install link:https://github.com/tekezo/Karabiner-Elements[Karabiner-Elements]
* Put `hammerspoon/init.lua` in `~/.hammerspoon/init.lua`
* Put `karabinier/karabiner.json` in `~/.config/karabinier/karabiner.json`

That's pretty much it.

== Configuration:

* The current configuration assumes that `CapsLock` has been disabled in System Preferences.
* The `CapsLock` key is defined as a new `HYPER` key (`Cmd`, `Option`, `Shift`, `Control`).
* The following shortcuts are defined to launch an app, or focus if it is already running:
** `HYPER+O`: "Microsoft Outlook"
** `HYPER+F`: "Finder"
** `HYPER+E`: "Sublime Text"
** `HYPER+S`: "Slack"
** `HYPER+C`: "Google Chrome"
* The following general shortcuts are defined:
** `HYPER+H`: Hide all windows.
** `HYPER+T`: Invoke iTerm2 visor (hotkey full-screen terminal window).
** `HYPER+L`: Lock screen.
* If `HYPER` is pressed on its own, it emulates `ESCAPE`.
